name: "fetch-tfstate"
description: "Fetch Terraform Cloud tfstate on GitHub Actions"
inputs:
  terraform-cloud-token:
    description: "Terraform Cloud token (Team API Token assumed)"
    required: true
  workspace-id:
    description: "Terraform Cloud workspace ID"
    required: true
outputs:
  tfstate:
    description: "Terraform Cloud tfstate"
    value: ${{ steps.fetch-tfstate.outputs.tfstate }}
runs:
  using: "composite"
  steps:
    - name: Fetch Terraform Cloud tfstate
      id: fetch-tfstate
      run: |
        set -euxo pipefail
        HTTP_RESPONSE=$(curl \
          --header "Authorization: Bearer "${{ inputs.terraform-cloud-token }}"" \
          --header "Content-Type: application/vnd.api+json" \
          "https://app.terraform.io/api/v2/workspaces/${{ inputs.workspace-id }}/current-state-version" | jq -r '.data | .attributes | ."hosted-state-download-url"')
        curl -o current.tfstate $HTTP_RESPONSE
        echo "::set-output name=tfstate::$(cat current.tfstate)"
      shell: bash
